'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'ja' | 'en' | 'es' | 'pt' | 'de' | 'fr' | 'zh' | 'ko' | 'it' | 'id' | 'ru' | 'tr' | 'nl' | 'pl' | 'th' | 'vi' | 'ar' | 'hi' | 'fa'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  ja: {
    // Header
    'header.privacy': 'プライバシー',
    'header.terms': '利用規約',
    'header.contact': 'お問い合わせ',

    // Home - Hero
    'home.hero.badge': 'トレーニング記録アプリ',
    'home.hero.tagline': '記録を重ね、進化を続ける',
    'home.hero.description': 'シンプルで直感的なトレーニング記録で、\nあなたの成長を可視化します',
    'home.hero.download': 'App Storeでダウンロード',

    // Home - Features
    'home.features.title': '主な機能',
    'home.features.subtitle': 'MASCALEがあなたのトレーニングをサポート',
    'home.features.calendar.title': 'カレンダー記録',
    'home.features.calendar.description': 'カレンダー形式でトレーニングの履歴を一目で確認。いつ、何をトレーニングしたか簡単に管理できます。',
    'home.features.detailed.title': '詳細なトレーニング記録',
    'home.features.detailed.description': 'エクササイズごとにセット数、重量、レップ数を記録。総ボリュームも自動計算されます。',
    'home.features.bodypart.title': '部位別管理',
    'home.features.bodypart.description': '胸、肩、腕、背中、脚、腹筋など、部位ごとにエクササイズを分類して管理できます。',
    'home.features.multilang.title': '19言語対応',
    'home.features.multilang.description': '日本語、英語、スペイン語、中国語、韓国語など19の言語に対応しています。',
    'home.features.units.title': '単位切り替え',
    'home.features.units.description': '重量単位をキログラム(kg)とポンド(lb)で切り替え可能。お好みの単位で記録できます。',
    'home.features.darkmode.title': 'ダークモード対応',
    'home.features.darkmode.description': 'ライト・ダークモード、システム設定に従う、の3つから選択可能です。',

    // Home - Languages
    'home.languages.title': '対応言語',
    'home.languages.subtitle': '世界中のユーザーに対応',

    // Footer
    'footer.tagline': '記録を重ね、進化を続ける',
    'footer.links': 'リンク',
    'footer.privacy': 'プライバシーポリシー',
    'footer.terms': '利用規約',
    'footer.contact': 'お問い合わせ',
    'footer.contact.title': 'お問い合わせ',

    // Privacy Page
    'privacy.title': 'プライバシーポリシー',
    'privacy.updated': '最終更新日: 2025年10月4日',

    // Terms Page
    'terms.title': '利用規約',
    'terms.updated': '最終更新日: 2025年10月4日',

    // Contact Page
    'contact.title': 'お問い合わせ',
    'contact.description': 'MASCALE に関するご質問、ご意見、不具合の報告などは、お気軽にお問い合わせください',
    'contact.email.title': 'メールでのお問い合わせ',
    'contact.language.title': '対応言語',
    'contact.language.value': '日本語のみ',
    'contact.response.title': 'レスポンス',
    'contact.response.value': '迅速に対応いたします',
  },
  en: {
    // Header
    'header.privacy': 'Privacy',
    'header.terms': 'Terms',
    'header.contact': 'Contact',

    // Home - Hero
    'home.hero.badge': 'Training Log App',
    'home.hero.tagline': 'Record and Keep Evolving',
    'home.hero.description': 'Visualize your progress with simple and\nintuitive training records',
    'home.hero.download': 'Download on the App Store',

    // Home - Features
    'home.features.title': 'Key Features',
    'home.features.subtitle': 'MASCALE supports your training',
    'home.features.calendar.title': 'Calendar Records',
    'home.features.calendar.description': 'View your training history at a glance in calendar format. Easily manage when and what you trained.',
    'home.features.detailed.title': 'Detailed Training Records',
    'home.features.detailed.description': 'Record sets, weight, and reps for each exercise. Total volume is automatically calculated.',
    'home.features.bodypart.title': 'Body Part Management',
    'home.features.bodypart.description': 'Organize exercises by body parts such as chest, shoulders, arms, back, legs, and abs.',
    'home.features.multilang.title': '19 Language Support',
    'home.features.multilang.description': 'Supports 19 languages including Japanese, English, Spanish, Chinese, and Korean.',
    'home.features.units.title': 'Unit Switching',
    'home.features.units.description': 'Switch weight units between kilograms (kg) and pounds (lb). Record in your preferred unit.',
    'home.features.darkmode.title': 'Dark Mode Support',
    'home.features.darkmode.description': 'Choose from light mode, dark mode, or follow system settings.',

    // Home - Languages
    'home.languages.title': 'Supported Languages',
    'home.languages.subtitle': 'Available for users worldwide',

    // Footer
    'footer.tagline': 'Record and Keep Evolving',
    'footer.links': 'Links',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact',
    'footer.contact.title': 'Contact Us',

    // Privacy Page
    'privacy.title': 'Privacy Policy',
    'privacy.updated': 'Last Updated: October 4, 2025',

    // Terms Page
    'terms.title': 'Terms of Service',
    'terms.updated': 'Last Updated: October 4, 2025',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.description': 'Feel free to contact us with any questions, feedback, or bug reports about MASCALE',
    'contact.email.title': 'Contact by Email',
    'contact.language.title': 'Supported Language',
    'contact.language.value': 'Japanese only',
    'contact.response.title': 'Response',
    'contact.response.value': 'We will respond promptly',
  },
  es: {
    'header.privacy': 'Privacidad',
    'header.terms': 'Términos',
    'header.contact': 'Contacto',
    'home.hero.badge': 'Aplicación de Registro de Entrenamiento',
    'home.hero.tagline': 'Registra y Sigue Evolucionando',
    'home.hero.description': 'Visualiza tu progreso con registros de\nentrenamiento simples e intuitivos',
    'home.hero.download': 'Descargar en la App Store',
    'home.features.title': 'Características Principales',
    'home.features.subtitle': 'MASCALE apoya tu entrenamiento',
    'home.features.calendar.title': 'Registros de Calendario',
    'home.features.calendar.description': 'Ve tu historial de entrenamiento de un vistazo en formato de calendario. Gestiona fácilmente cuándo y qué entrenaste.',
    'home.features.detailed.title': 'Registros Detallados de Entrenamiento',
    'home.features.detailed.description': 'Registra series, peso y repeticiones para cada ejercicio. El volumen total se calcula automáticamente.',
    'home.features.bodypart.title': 'Gestión por Parte del Cuerpo',
    'home.features.bodypart.description': 'Organiza ejercicios por partes del cuerpo como pecho, hombros, brazos, espalda, piernas y abdominales.',
    'home.features.multilang.title': 'Soporte para 19 Idiomas',
    'home.features.multilang.description': 'Soporta 19 idiomas incluyendo japonés, inglés, español, chino y coreano.',
    'home.features.units.title': 'Cambio de Unidades',
    'home.features.units.description': 'Cambia las unidades de peso entre kilogramos (kg) y libras (lb). Registra en tu unidad preferida.',
    'home.features.darkmode.title': 'Soporte para Modo Oscuro',
    'home.features.darkmode.description': 'Elige entre modo claro, modo oscuro o seguir la configuración del sistema.',
    'home.languages.title': 'Idiomas Soportados',
    'home.languages.subtitle': 'Disponible para usuarios en todo el mundo',
    'footer.tagline': 'Registra y Sigue Evolucionando',
    'footer.links': 'Enlaces',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contacto',
    'footer.contact.title': 'Contáctenos',
    'privacy.title': 'Política de Privacidad',
    'privacy.updated': 'Última actualización: 4 de octubre de 2025',
    'terms.title': 'Términos de Servicio',
    'terms.updated': 'Última actualización: 4 de octubre de 2025',
    'contact.title': 'Contáctenos',
    'contact.description': 'No dude en contactarnos con cualquier pregunta, comentario o informe de errores sobre MASCALE',
    'contact.email.title': 'Contacto por Correo Electrónico',
    'contact.language.title': 'Idioma Soportado',
    'contact.language.value': 'Solo japonés',
    'contact.response.title': 'Respuesta',
    'contact.response.value': 'Responderemos rápidamente',
  },
  pt: {
    'header.privacy': 'Privacidade',
    'header.terms': 'Termos',
    'header.contact': 'Contato',
    'home.hero.badge': 'Aplicativo de Registro de Treino',
    'home.hero.tagline': 'Registre e Continue Evoluindo',
    'home.hero.description': 'Visualize seu progresso com registros de\ntreino simples e intuitivos',
    'home.hero.download': 'Baixar na App Store',
    'home.features.title': 'Principais Recursos',
    'home.features.subtitle': 'MASCALE apoia seu treino',
    'home.features.calendar.title': 'Registros de Calendário',
    'home.features.calendar.description': 'Veja seu histórico de treino rapidamente em formato de calendário. Gerencie facilmente quando e o que você treinou.',
    'home.features.detailed.title': 'Registros Detalhados de Treino',
    'home.features.detailed.description': 'Registre séries, peso e repetições para cada exercício. O volume total é calculado automaticamente.',
    'home.features.bodypart.title': 'Gestão por Parte do Corpo',
    'home.features.bodypart.description': 'Organize exercícios por partes do corpo como peito, ombros, braços, costas, pernas e abdômen.',
    'home.features.multilang.title': 'Suporte para 19 Idiomas',
    'home.features.multilang.description': 'Suporta 19 idiomas incluindo japonês, inglês, espanhol, chinês e coreano.',
    'home.features.units.title': 'Troca de Unidades',
    'home.features.units.description': 'Troque unidades de peso entre quilogramas (kg) e libras (lb). Registre na sua unidade preferida.',
    'home.features.darkmode.title': 'Suporte para Modo Escuro',
    'home.features.darkmode.description': 'Escolha entre modo claro, modo escuro ou seguir as configurações do sistema.',
    'home.languages.title': 'Idiomas Suportados',
    'home.languages.subtitle': 'Disponível para usuários em todo o mundo',
    'footer.tagline': 'Registre e Continue Evoluindo',
    'footer.links': 'Links',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.contact': 'Contato',
    'footer.contact.title': 'Entre em Contato',
    'privacy.title': 'Política de Privacidade',
    'privacy.updated': 'Última atualização: 4 de outubro de 2025',
    'terms.title': 'Termos de Serviço',
    'terms.updated': 'Última atualização: 4 de outubro de 2025',
    'contact.title': 'Entre em Contato',
    'contact.description': 'Sinta-se à vontade para entrar em contato conosco com qualquer dúvida, comentário ou relatório de bug sobre MASCALE',
    'contact.email.title': 'Contato por E-mail',
    'contact.language.title': 'Idioma Suportado',
    'contact.language.value': 'Apenas japonês',
    'contact.response.title': 'Resposta',
    'contact.response.value': 'Responderemos prontamente',
  },
  de: {
    'header.privacy': 'Datenschutz',
    'header.terms': 'Bedingungen',
    'header.contact': 'Kontakt',
    'home.hero.badge': 'Trainingsprotokoll-App',
    'home.hero.tagline': 'Aufzeichnen und Weiterentwickeln',
    'home.hero.description': 'Visualisieren Sie Ihren Fortschritt mit einfachen\nund intuitiven Trainingsprotokollen',
    'home.hero.download': 'Im App Store herunterladen',
    'home.features.title': 'Hauptfunktionen',
    'home.features.subtitle': 'MASCALE unterstützt Ihr Training',
    'home.features.calendar.title': 'Kalenderaufzeichnungen',
    'home.features.calendar.description': 'Sehen Sie Ihre Trainingshistorie auf einen Blick im Kalenderformat. Verwalten Sie einfach, wann und was Sie trainiert haben.',
    'home.features.detailed.title': 'Detaillierte Trainingsaufzeichnungen',
    'home.features.detailed.description': 'Zeichnen Sie Sätze, Gewicht und Wiederholungen für jede Übung auf. Das Gesamtvolumen wird automatisch berechnet.',
    'home.features.bodypart.title': 'Körperteil-Management',
    'home.features.bodypart.description': 'Organisieren Sie Übungen nach Körperteilen wie Brust, Schultern, Arme, Rücken, Beine und Bauch.',
    'home.features.multilang.title': 'Unterstützung für 19 Sprachen',
    'home.features.multilang.description': 'Unterstützt 19 Sprachen einschließlich Japanisch, Englisch, Spanisch, Chinesisch und Koreanisch.',
    'home.features.units.title': 'Einheitenwechsel',
    'home.features.units.description': 'Wechseln Sie Gewichtseinheiten zwischen Kilogramm (kg) und Pfund (lb). Zeichnen Sie in Ihrer bevorzugten Einheit auf.',
    'home.features.darkmode.title': 'Dark Mode-Unterstützung',
    'home.features.darkmode.description': 'Wählen Sie zwischen hellem Modus, dunklem Modus oder folgen Sie den Systemeinstellungen.',
    'home.languages.title': 'Unterstützte Sprachen',
    'home.languages.subtitle': 'Verfügbar für Benutzer weltweit',
    'footer.tagline': 'Aufzeichnen und Weiterentwickeln',
    'footer.links': 'Links',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.contact': 'Kontakt',
    'footer.contact.title': 'Kontaktieren Sie uns',
    'privacy.title': 'Datenschutzrichtlinie',
    'privacy.updated': 'Zuletzt aktualisiert: 4. Oktober 2025',
    'terms.title': 'Nutzungsbedingungen',
    'terms.updated': 'Zuletzt aktualisiert: 4. Oktober 2025',
    'contact.title': 'Kontaktieren Sie uns',
    'contact.description': 'Kontaktieren Sie uns gerne bei Fragen, Feedback oder Fehlerberichten zu MASCALE',
    'contact.email.title': 'Kontakt per E-Mail',
    'contact.language.title': 'Unterstützte Sprache',
    'contact.language.value': 'Nur Japanisch',
    'contact.response.title': 'Antwort',
    'contact.response.value': 'Wir werden umgehend antworten',
  },
  fr: {
    'header.privacy': 'Confidentialité',
    'header.terms': 'Conditions',
    'header.contact': 'Contact',
    'home.hero.badge': 'Application de Journal d\'Entraînement',
    'home.hero.tagline': 'Enregistrer et Continuer à Évoluer',
    'home.hero.description': 'Visualisez votre progression avec des enregistrements\nd\'entraînement simples et intuitifs',
    'home.hero.download': 'Télécharger sur l\'App Store',
    'home.features.title': 'Fonctionnalités Principales',
    'home.features.subtitle': 'MASCALE soutient votre entraînement',
    'home.features.calendar.title': 'Enregistrements de Calendrier',
    'home.features.calendar.description': 'Consultez votre historique d\'entraînement en un coup d\'œil au format calendrier. Gérez facilement quand et quoi vous avez entraîné.',
    'home.features.detailed.title': 'Enregistrements Détaillés d\'Entraînement',
    'home.features.detailed.description': 'Enregistrez les séries, le poids et les répétitions pour chaque exercice. Le volume total est calculé automatiquement.',
    'home.features.bodypart.title': 'Gestion par Partie du Corps',
    'home.features.bodypart.description': 'Organisez les exercices par parties du corps comme la poitrine, les épaules, les bras, le dos, les jambes et les abdominaux.',
    'home.features.multilang.title': 'Support de 19 Langues',
    'home.features.multilang.description': 'Prend en charge 19 langues dont le japonais, l\'anglais, l\'espagnol, le chinois et le coréen.',
    'home.features.units.title': 'Changement d\'Unités',
    'home.features.units.description': 'Changez les unités de poids entre kilogrammes (kg) et livres (lb). Enregistrez dans votre unité préférée.',
    'home.features.darkmode.title': 'Support du Mode Sombre',
    'home.features.darkmode.description': 'Choisissez entre mode clair, mode sombre ou suivre les paramètres système.',
    'home.languages.title': 'Langues Supportées',
    'home.languages.subtitle': 'Disponible pour les utilisateurs du monde entier',
    'footer.tagline': 'Enregistrer et Continuer à Évoluer',
    'footer.links': 'Liens',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.contact': 'Contact',
    'footer.contact.title': 'Contactez-nous',
    'privacy.title': 'Politique de Confidentialité',
    'privacy.updated': 'Dernière mise à jour : 4 octobre 2025',
    'terms.title': 'Conditions d\'Utilisation',
    'terms.updated': 'Dernière mise à jour : 4 octobre 2025',
    'contact.title': 'Contactez-nous',
    'contact.description': 'N\'hésitez pas à nous contacter pour toute question, commentaire ou rapport de bug concernant MASCALE',
    'contact.email.title': 'Contact par E-mail',
    'contact.language.title': 'Langue Supportée',
    'contact.language.value': 'Japonais uniquement',
    'contact.response.title': 'Réponse',
    'contact.response.value': 'Nous répondrons rapidement',
  },
  zh: {
    'header.privacy': '隐私',
    'header.terms': '条款',
    'header.contact': '联系',
    'home.hero.badge': '训练记录应用',
    'home.hero.tagline': '记录并持续进化',
    'home.hero.description': '通过简单直观的训练记录\n可视化您的进步',
    'home.hero.download': '在 App Store 下载',
    'home.features.title': '主要功能',
    'home.features.subtitle': 'MASCALE 支持您的训练',
    'home.features.calendar.title': '日历记录',
    'home.features.calendar.description': '以日历格式一目了然地查看您的训练历史。轻松管理何时训练了什么。',
    'home.features.detailed.title': '详细的训练记录',
    'home.features.detailed.description': '记录每个练习的组数、重量和次数。总量自动计算。',
    'home.features.bodypart.title': '部位管理',
    'home.features.bodypart.description': '按身体部位组织练习，如胸部、肩部、手臂、背部、腿部和腹部。',
    'home.features.multilang.title': '支持19种语言',
    'home.features.multilang.description': '支持19种语言，包括日语、英语、西班牙语、中文和韩语。',
    'home.features.units.title': '单位切换',
    'home.features.units.description': '在千克(kg)和磅(lb)之间切换重量单位。以您喜欢的单位记录。',
    'home.features.darkmode.title': '深色模式支持',
    'home.features.darkmode.description': '在浅色模式、深色模式之间选择或跟随系统设置。',
    'home.languages.title': '支持的语言',
    'home.languages.subtitle': '为全球用户提供服务',
    'footer.tagline': '记录并持续进化',
    'footer.links': '链接',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.contact': '联系',
    'footer.contact.title': '联系我们',
    'privacy.title': '隐私政策',
    'privacy.updated': '最后更新：2025年10月4日',
    'terms.title': '服务条款',
    'terms.updated': '最后更新：2025年10月4日',
    'contact.title': '联系我们',
    'contact.description': '如有关于 MASCALE 的任何问题、反馈或错误报告，请随时与我们联系',
    'contact.email.title': '电子邮件联系',
    'contact.language.title': '支持的语言',
    'contact.language.value': '仅日语',
    'contact.response.title': '响应',
    'contact.response.value': '我们将迅速回复',
  },
  ko: {
    'header.privacy': '개인정보',
    'header.terms': '이용약관',
    'header.contact': '문의',
    'home.hero.badge': '운동 기록 앱',
    'home.hero.tagline': '기록하고 계속 발전하기',
    'home.hero.description': '간단하고 직관적인 운동 기록으로\n진행 상황을 시각화하세요',
    'home.hero.download': 'App Store에서 다운로드',
    'home.features.title': '주요 기능',
    'home.features.subtitle': 'MASCALE이 운동을 지원합니다',
    'home.features.calendar.title': '캘린더 기록',
    'home.features.calendar.description': '캘린더 형식으로 운동 기록을 한눈에 확인하세요. 언제 무엇을 운동했는지 쉽게 관리할 수 있습니다.',
    'home.features.detailed.title': '상세한 운동 기록',
    'home.features.detailed.description': '각 운동의 세트, 무게, 반복 횟수를 기록하세요. 총 볼륨은 자동으로 계산됩니다.',
    'home.features.bodypart.title': '부위별 관리',
    'home.features.bodypart.description': '가슴, 어깨, 팔, 등, 다리, 복근과 같은 신체 부위별로 운동을 정리하세요.',
    'home.features.multilang.title': '19개 언어 지원',
    'home.features.multilang.description': '일본어, 영어, 스페인어, 중국어, 한국어를 포함한 19개 언어를 지원합니다.',
    'home.features.units.title': '단위 전환',
    'home.features.units.description': '킬로그램(kg)과 파운드(lb) 사이에서 무게 단위를 전환하세요. 선호하는 단위로 기록하세요.',
    'home.features.darkmode.title': '다크 모드 지원',
    'home.features.darkmode.description': '라이트 모드, 다크 모드 중에서 선택하거나 시스템 설정을 따르세요.',
    'home.languages.title': '지원 언어',
    'home.languages.subtitle': '전 세계 사용자를 위해 제공',
    'footer.tagline': '기록하고 계속 발전하기',
    'footer.links': '링크',
    'footer.privacy': '개인정보 보호정책',
    'footer.terms': '서비스 약관',
    'footer.contact': '문의',
    'footer.contact.title': '문의하기',
    'privacy.title': '개인정보 보호정책',
    'privacy.updated': '최종 업데이트: 2025년 10월 4일',
    'terms.title': '서비스 약관',
    'terms.updated': '최종 업데이트: 2025년 10월 4일',
    'contact.title': '문의하기',
    'contact.description': 'MASCALE에 대한 질문, 피드백 또는 버그 보고는 언제든지 문의해 주세요',
    'contact.email.title': '이메일로 문의',
    'contact.language.title': '지원 언어',
    'contact.language.value': '일본어만',
    'contact.response.title': '응답',
    'contact.response.value': '신속하게 응답하겠습니다',
  },
  it: {
    'header.privacy': 'Privacy',
    'header.terms': 'Termini',
    'header.contact': 'Contatto',
    'home.hero.badge': 'App per il Registro degli Allenamenti',
    'home.hero.tagline': 'Registra e Continua a Evolvere',
    'home.hero.description': 'Visualizza i tuoi progressi con registri di\nallenamento semplici e intuitivi',
    'home.hero.download': 'Scarica dall\'App Store',
    'home.features.title': 'Caratteristiche Principali',
    'home.features.subtitle': 'MASCALE supporta il tuo allenamento',
    'home.features.calendar.title': 'Registri del Calendario',
    'home.features.calendar.description': 'Visualizza la cronologia degli allenamenti a colpo d\'occhio in formato calendario. Gestisci facilmente quando e cosa hai allenato.',
    'home.features.detailed.title': 'Registri Dettagliati degli Allenamenti',
    'home.features.detailed.description': 'Registra serie, peso e ripetizioni per ogni esercizio. Il volume totale viene calcolato automaticamente.',
    'home.features.bodypart.title': 'Gestione per Parte del Corpo',
    'home.features.bodypart.description': 'Organizza gli esercizi per parti del corpo come petto, spalle, braccia, schiena, gambe e addominali.',
    'home.features.multilang.title': 'Supporto per 19 Lingue',
    'home.features.multilang.description': 'Supporta 19 lingue tra cui giapponese, inglese, spagnolo, cinese e coreano.',
    'home.features.units.title': 'Cambio di Unità',
    'home.features.units.description': 'Cambia le unità di peso tra chilogrammi (kg) e libbre (lb). Registra nella tua unità preferita.',
    'home.features.darkmode.title': 'Supporto Modalità Scura',
    'home.features.darkmode.description': 'Scegli tra modalità chiara, modalità scura o segui le impostazioni di sistema.',
    'home.languages.title': 'Lingue Supportate',
    'home.languages.subtitle': 'Disponibile per utenti in tutto il mondo',
    'footer.tagline': 'Registra e Continua a Evolvere',
    'footer.links': 'Collegamenti',
    'footer.privacy': 'Informativa sulla Privacy',
    'footer.terms': 'Termini di Servizio',
    'footer.contact': 'Contatto',
    'footer.contact.title': 'Contattaci',
    'privacy.title': 'Informativa sulla Privacy',
    'privacy.updated': 'Ultimo aggiornamento: 4 ottobre 2025',
    'terms.title': 'Termini di Servizio',
    'terms.updated': 'Ultimo aggiornamento: 4 ottobre 2025',
    'contact.title': 'Contattaci',
    'contact.description': 'Non esitare a contattarci per domande, feedback o segnalazioni di bug su MASCALE',
    'contact.email.title': 'Contatto via Email',
    'contact.language.title': 'Lingua Supportata',
    'contact.language.value': 'Solo giapponese',
    'contact.response.title': 'Risposta',
    'contact.response.value': 'Risponderemo prontamente',
  },
  id: {
    'header.privacy': 'Privasi',
    'header.terms': 'Ketentuan',
    'header.contact': 'Kontak',
    'home.hero.badge': 'Aplikasi Catatan Latihan',
    'home.hero.tagline': 'Catat dan Terus Berkembang',
    'home.hero.description': 'Visualisasikan kemajuan Anda dengan catatan\nlatihan yang sederhana dan intuitif',
    'home.hero.download': 'Unduh di App Store',
    'home.features.title': 'Fitur Utama',
    'home.features.subtitle': 'MASCALE mendukung latihan Anda',
    'home.features.calendar.title': 'Catatan Kalender',
    'home.features.calendar.description': 'Lihat riwayat latihan Anda sekilas dalam format kalender. Kelola dengan mudah kapan dan apa yang Anda latih.',
    'home.features.detailed.title': 'Catatan Latihan Terperinci',
    'home.features.detailed.description': 'Catat set, berat, dan repetisi untuk setiap latihan. Volume total dihitung secara otomatis.',
    'home.features.bodypart.title': 'Manajemen Bagian Tubuh',
    'home.features.bodypart.description': 'Atur latihan berdasarkan bagian tubuh seperti dada, bahu, lengan, punggung, kaki, dan perut.',
    'home.features.multilang.title': 'Dukungan 19 Bahasa',
    'home.features.multilang.description': 'Mendukung 19 bahasa termasuk Jepang, Inggris, Spanyol, Cina, dan Korea.',
    'home.features.units.title': 'Pergantian Unit',
    'home.features.units.description': 'Alihkan unit berat antara kilogram (kg) dan pon (lb). Catat dalam unit pilihan Anda.',
    'home.features.darkmode.title': 'Dukungan Mode Gelap',
    'home.features.darkmode.description': 'Pilih antara mode terang, mode gelap, atau ikuti pengaturan sistem.',
    'home.languages.title': 'Bahasa yang Didukung',
    'home.languages.subtitle': 'Tersedia untuk pengguna di seluruh dunia',
    'footer.tagline': 'Catat dan Terus Berkembang',
    'footer.links': 'Tautan',
    'footer.privacy': 'Kebijakan Privasi',
    'footer.terms': 'Ketentuan Layanan',
    'footer.contact': 'Kontak',
    'footer.contact.title': 'Hubungi Kami',
    'privacy.title': 'Kebijakan Privasi',
    'privacy.updated': 'Terakhir diperbarui: 4 Oktober 2025',
    'terms.title': 'Ketentuan Layanan',
    'terms.updated': 'Terakhir diperbarui: 4 Oktober 2025',
    'contact.title': 'Hubungi Kami',
    'contact.description': 'Jangan ragu untuk menghubungi kami dengan pertanyaan, masukan, atau laporan bug tentang MASCALE',
    'contact.email.title': 'Kontak melalui Email',
    'contact.language.title': 'Bahasa yang Didukung',
    'contact.language.value': 'Hanya Jepang',
    'contact.response.title': 'Respons',
    'contact.response.value': 'Kami akan merespons dengan cepat',
  },
  ru: {
    'header.privacy': 'Конфиденциальность',
    'header.terms': 'Условия',
    'header.contact': 'Контакт',
    'home.hero.badge': 'Приложение для записи тренировок',
    'home.hero.tagline': 'Записывайте и продолжайте развиваться',
    'home.hero.description': 'Визуализируйте свой прогресс с помощью простых и\nинтуитивных записей тренировок',
    'home.hero.download': 'Загрузить в App Store',
    'home.features.title': 'Основные функции',
    'home.features.subtitle': 'MASCALE поддерживает ваши тренировки',
    'home.features.calendar.title': 'Календарные записи',
    'home.features.calendar.description': 'Просматривайте историю тренировок с первого взгляда в формате календаря. Легко управляйте тем, когда и что вы тренировали.',
    'home.features.detailed.title': 'Подробные записи тренировок',
    'home.features.detailed.description': 'Записывайте подходы, вес и повторения для каждого упражнения. Общий объем рассчитывается автоматически.',
    'home.features.bodypart.title': 'Управление частями тела',
    'home.features.bodypart.description': 'Организуйте упражнения по частям тела, таким как грудь, плечи, руки, спина, ноги и пресс.',
    'home.features.multilang.title': 'Поддержка 19 языков',
    'home.features.multilang.description': 'Поддерживает 19 языков, включая японский, английский, испанский, китайский и корейский.',
    'home.features.units.title': 'Переключение единиц',
    'home.features.units.description': 'Переключайте единицы веса между килограммами (кг) и фунтами (фунты). Записывайте в предпочитаемых единицах.',
    'home.features.darkmode.title': 'Поддержка темного режима',
    'home.features.darkmode.description': 'Выберите светлый режим, темный режим или следуйте системным настройкам.',
    'home.languages.title': 'Поддерживаемые языки',
    'home.languages.subtitle': 'Доступно для пользователей по всему миру',
    'footer.tagline': 'Записывайте и продолжайте развиваться',
    'footer.links': 'Ссылки',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия обслуживания',
    'footer.contact': 'Контакт',
    'footer.contact.title': 'Свяжитесь с нами',
    'privacy.title': 'Политика конфиденциальности',
    'privacy.updated': 'Последнее обновление: 4 октября 2025 г.',
    'terms.title': 'Условия обслуживания',
    'terms.updated': 'Последнее обновление: 4 октября 2025 г.',
    'contact.title': 'Свяжитесь с нами',
    'contact.description': 'Не стесняйтесь обращаться к нам с любыми вопросами, отзывами или отчетами об ошибках о MASCALE',
    'contact.email.title': 'Контакт по электронной почте',
    'contact.language.title': 'Поддерживаемый язык',
    'contact.language.value': 'Только японский',
    'contact.response.title': 'Ответ',
    'contact.response.value': 'Мы ответим быстро',
  },
  tr: {
    'header.privacy': 'Gizlilik',
    'header.terms': 'Şartlar',
    'header.contact': 'İletişim',
    'home.hero.badge': 'Antrenman Kaydı Uygulaması',
    'home.hero.tagline': 'Kaydet ve Gelişmeye Devam Et',
    'home.hero.description': 'Basit ve sezgisel antrenman kayıtlarıyla\nilerlemenizi görselleştirin',
    'home.hero.download': 'App Store\'dan İndirin',
    'home.features.title': 'Ana Özellikler',
    'home.features.subtitle': 'MASCALE antrenmanınızı destekler',
    'home.features.calendar.title': 'Takvim Kayıtları',
    'home.features.calendar.description': 'Antrenman geçmişinizi takvim formatında bir bakışta görün. Ne zaman ve ne antrenman yaptığınızı kolayca yönetin.',
    'home.features.detailed.title': 'Detaylı Antrenman Kayıtları',
    'home.features.detailed.description': 'Her egzersiz için set, ağırlık ve tekrar sayısını kaydedin. Toplam hacim otomatik olarak hesaplanır.',
    'home.features.bodypart.title': 'Vücut Bölümü Yönetimi',
    'home.features.bodypart.description': 'Göğüs, omuzlar, kollar, sırt, bacaklar ve karın gibi vücut bölümlerine göre egzersizleri düzenleyin.',
    'home.features.multilang.title': '19 Dil Desteği',
    'home.features.multilang.description': 'Japonca, İngilizce, İspanyolca, Çince ve Korece dahil 19 dili destekler.',
    'home.features.units.title': 'Birim Değiştirme',
    'home.features.units.description': 'Ağırlık birimlerini kilogram (kg) ve pound (lb) arasında değiştirin. Tercih ettiğiniz birimde kaydedin.',
    'home.features.darkmode.title': 'Karanlık Mod Desteği',
    'home.features.darkmode.description': 'Açık mod, karanlık mod arasından seçim yapın veya sistem ayarlarını izleyin.',
    'home.languages.title': 'Desteklenen Diller',
    'home.languages.subtitle': 'Dünya çapında kullanıcılar için kullanılabilir',
    'footer.tagline': 'Kaydet ve Gelişmeye Devam Et',
    'footer.links': 'Bağlantılar',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Hizmet Şartları',
    'footer.contact': 'İletişim',
    'footer.contact.title': 'Bize Ulaşın',
    'privacy.title': 'Gizlilik Politikası',
    'privacy.updated': 'Son güncelleme: 4 Ekim 2025',
    'terms.title': 'Hizmet Şartları',
    'terms.updated': 'Son güncelleme: 4 Ekim 2025',
    'contact.title': 'Bize Ulaşın',
    'contact.description': 'MASCALE hakkında sorularınız, geri bildirimleriniz veya hata raporlarınız için bize ulaşmaktan çekinmeyin',
    'contact.email.title': 'E-posta ile İletişim',
    'contact.language.title': 'Desteklenen Dil',
    'contact.language.value': 'Sadece Japonca',
    'contact.response.title': 'Yanıt',
    'contact.response.value': 'Hızlı bir şekilde yanıt vereceğiz',
  },
  nl: {
    'header.privacy': 'Privacy',
    'header.terms': 'Voorwaarden',
    'header.contact': 'Contact',
    'home.hero.badge': 'Trainingslog App',
    'home.hero.tagline': 'Registreer en Blijf Evolueren',
    'home.hero.description': 'Visualiseer je voortgang met eenvoudige en\nintuïtieve trainingsregistraties',
    'home.hero.download': 'Download op de App Store',
    'home.features.title': 'Belangrijkste Functies',
    'home.features.subtitle': 'MASCALE ondersteunt je training',
    'home.features.calendar.title': 'Kalenderregistraties',
    'home.features.calendar.description': 'Bekijk je trainingsgeschiedenis in één oogopslag in kalenderformaat. Beheer eenvoudig wanneer en wat je hebt getraind.',
    'home.features.detailed.title': 'Gedetailleerde Trainingsregistraties',
    'home.features.detailed.description': 'Registreer sets, gewicht en herhalingen voor elke oefening. Totaal volume wordt automatisch berekend.',
    'home.features.bodypart.title': 'Lichaamsdeel Beheer',
    'home.features.bodypart.description': 'Organiseer oefeningen per lichaamsdeel zoals borst, schouders, armen, rug, benen en buik.',
    'home.features.multilang.title': 'Ondersteuning voor 19 Talen',
    'home.features.multilang.description': 'Ondersteunt 19 talen waaronder Japans, Engels, Spaans, Chinees en Koreaans.',
    'home.features.units.title': 'Eenheid Wisselen',
    'home.features.units.description': 'Wissel gewichtseenheden tussen kilogrammen (kg) en ponden (lb). Registreer in je voorkeursunit.',
    'home.features.darkmode.title': 'Donkere Modus Ondersteuning',
    'home.features.darkmode.description': 'Kies tussen lichte modus, donkere modus of volg systeeminstellingen.',
    'home.languages.title': 'Ondersteunde Talen',
    'home.languages.subtitle': 'Beschikbaar voor gebruikers wereldwijd',
    'footer.tagline': 'Registreer en Blijf Evolueren',
    'footer.links': 'Links',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Servicevoorwaarden',
    'footer.contact': 'Contact',
    'footer.contact.title': 'Neem Contact Op',
    'privacy.title': 'Privacybeleid',
    'privacy.updated': 'Laatst bijgewerkt: 4 oktober 2025',
    'terms.title': 'Servicevoorwaarden',
    'terms.updated': 'Laatst bijgewerkt: 4 oktober 2025',
    'contact.title': 'Neem Contact Op',
    'contact.description': 'Neem gerust contact met ons op met vragen, feedback of bugrapporten over MASCALE',
    'contact.email.title': 'Contact via E-mail',
    'contact.language.title': 'Ondersteunde Taal',
    'contact.language.value': 'Alleen Japans',
    'contact.response.title': 'Reactie',
    'contact.response.value': 'We zullen snel reageren',
  },
  pl: {
    'header.privacy': 'Prywatność',
    'header.terms': 'Warunki',
    'header.contact': 'Kontakt',
    'home.hero.badge': 'Aplikacja do Dziennika Treningowego',
    'home.hero.tagline': 'Zapisuj i Rozwijaj Się',
    'home.hero.description': 'Wizualizuj swoje postępy dzięki prostym i\nintuicyjnym zapisom treningowym',
    'home.hero.download': 'Pobierz w App Store',
    'home.features.title': 'Główne Funkcje',
    'home.features.subtitle': 'MASCALE wspiera Twoje treningi',
    'home.features.calendar.title': 'Zapisy Kalendarzowe',
    'home.features.calendar.description': 'Przeglądaj historię treningów na pierwszy rzut oka w formacie kalendarza. Łatwo zarządzaj tym, kiedy i co trenowałeś.',
    'home.features.detailed.title': 'Szczegółowe Zapisy Treningowe',
    'home.features.detailed.description': 'Zapisuj serie, wagę i powtórzenia dla każdego ćwiczenia. Całkowita objętość jest automatycznie obliczana.',
    'home.features.bodypart.title': 'Zarządzanie Częściami Ciała',
    'home.features.bodypart.description': 'Organizuj ćwiczenia według części ciała, takich jak klatka piersiowa, ramiona, ręce, plecy, nogi i brzuch.',
    'home.features.multilang.title': 'Wsparcie 19 Języków',
    'home.features.multilang.description': 'Obsługuje 19 języków, w tym japoński, angielski, hiszpański, chiński i koreański.',
    'home.features.units.title': 'Przełączanie Jednostek',
    'home.features.units.description': 'Przełączaj jednostki wagi między kilogramami (kg) a funtami (lb). Zapisuj w preferowanej jednostce.',
    'home.features.darkmode.title': 'Wsparcie Trybu Ciemnego',
    'home.features.darkmode.description': 'Wybierz tryb jasny, tryb ciemny lub postępuj zgodnie z ustawieniami systemu.',
    'home.languages.title': 'Obsługiwane Języki',
    'home.languages.subtitle': 'Dostępne dla użytkowników na całym świecie',
    'footer.tagline': 'Zapisuj i Rozwijaj Się',
    'footer.links': 'Linki',
    'footer.privacy': 'Polityka Prywatności',
    'footer.terms': 'Warunki Usługi',
    'footer.contact': 'Kontakt',
    'footer.contact.title': 'Skontaktuj Się z Nami',
    'privacy.title': 'Polityka Prywatności',
    'privacy.updated': 'Ostatnia aktualizacja: 4 października 2025',
    'terms.title': 'Warunki Usługi',
    'terms.updated': 'Ostatnia aktualizacja: 4 października 2025',
    'contact.title': 'Skontaktuj Się z Nami',
    'contact.description': 'Nie wahaj się skontaktować z nami w przypadku pytań, opinii lub raportów o błędach dotyczących MASCALE',
    'contact.email.title': 'Kontakt przez E-mail',
    'contact.language.title': 'Obsługiwany Język',
    'contact.language.value': 'Tylko japoński',
    'contact.response.title': 'Odpowiedź',
    'contact.response.value': 'Odpowiemy szybko',
  },
  th: {
    'header.privacy': 'ความเป็นส่วนตัว',
    'header.terms': 'ข้อกำหนด',
    'header.contact': 'ติดต่อ',
    'home.hero.badge': 'แอปบันทึกการออกกำลังกาย',
    'home.hero.tagline': 'บันทึกและพัฒนาต่อไป',
    'home.hero.description': 'มองเห็นความก้าวหน้าด้วยบันทึกการออกกำลังกาย\nที่เรียบง่ายและใช้งานง่าย',
    'home.hero.download': 'ดาวน์โหลดใน App Store',
    'home.features.title': 'ฟีเจอร์หลัก',
    'home.features.subtitle': 'MASCALE สนับสนุนการออกกำลังกายของคุณ',
    'home.features.calendar.title': 'บันทึกปฏิทิน',
    'home.features.calendar.description': 'ดูประวัติการออกกำลังกายได้ในรูปแบบปฏิทิน จัดการได้ง่ายว่าคุณออกกำลังกายเมื่อใดและอะไร',
    'home.features.detailed.title': 'บันทึกการออกกำลังกายโดยละเอียด',
    'home.features.detailed.description': 'บันทึกเซต น้ำหนัก และจำนวนครั้งสำหรับแต่ละแบบฝึกหัด ปริมาณรวมจะคำนวณโดยอัตโนมัติ',
    'home.features.bodypart.title': 'การจัดการตามส่วนของร่างกาย',
    'home.features.bodypart.description': 'จัดระเบียบแบบฝึกหัดตามส่วนของร่างกาย เช่น หน้าอก ไหล่ แขน หลัง ขา และหน้าท้อง',
    'home.features.multilang.title': 'รองรับ 19 ภาษา',
    'home.features.multilang.description': 'รองรับ 19 ภาษา รวมถึงญี่ปุ่น อังกฤษ สเปน จีน และเกาหลี',
    'home.features.units.title': 'การสลับหน่วย',
    'home.features.units.description': 'สลับหน่วยน้ำหนักระหว่างกิโลกรัม (kg) และปอนด์ (lb) บันทึกในหน่วยที่คุณชอบ',
    'home.features.darkmode.title': 'รองรับโหมดมืด',
    'home.features.darkmode.description': 'เลือกระหว่างโหมดสว่าง โหมดมืด หรือตามการตั้งค่าระบบ',
    'home.languages.title': 'ภาษาที่รองรับ',
    'home.languages.subtitle': 'พร้อมให้บริการผู้ใช้ทั่วโลก',
    'footer.tagline': 'บันทึกและพัฒนาต่อไป',
    'footer.links': 'ลิงก์',
    'footer.privacy': 'นโยบายความเป็นส่วนตัว',
    'footer.terms': 'เงื่อนไขการให้บริการ',
    'footer.contact': 'ติดต่อ',
    'footer.contact.title': 'ติดต่อเรา',
    'privacy.title': 'นโยบายความเป็นส่วนตัว',
    'privacy.updated': 'อัปเดตล่าสุด: 4 ตุลาคม 2025',
    'terms.title': 'เงื่อนไขการให้บริการ',
    'terms.updated': 'อัปเดตล่าสุด: 4 ตุลาคม 2025',
    'contact.title': 'ติดต่อเรา',
    'contact.description': 'อย่าลังเลที่จะติดต่อเราหากมีคำถาม ข้อเสนอแนะ หรือรายงานข้อบกพร่องเกี่ยวกับ MASCALE',
    'contact.email.title': 'ติดต่อทางอีเมล',
    'contact.language.title': 'ภาษาที่รองรับ',
    'contact.language.value': 'เฉพาะภาษาญี่ปุ่น',
    'contact.response.title': 'การตอบกลับ',
    'contact.response.value': 'เราจะตอบกลับอย่างรวดเร็ว',
  },
  vi: {
    'header.privacy': 'Quyền riêng tư',
    'header.terms': 'Điều khoản',
    'header.contact': 'Liên hệ',
    'home.hero.badge': 'Ứng Dụng Nhật Ký Tập Luyện',
    'home.hero.tagline': 'Ghi Chép và Tiếp Tục Phát Triển',
    'home.hero.description': 'Hình dung tiến trình của bạn với các bản ghi\ntập luyện đơn giản và trực quan',
    'home.hero.download': 'Tải xuống trên App Store',
    'home.features.title': 'Tính Năng Chính',
    'home.features.subtitle': 'MASCALE hỗ trợ tập luyện của bạn',
    'home.features.calendar.title': 'Bản Ghi Lịch',
    'home.features.calendar.description': 'Xem lịch sử tập luyện của bạn trong nháy mắt ở định dạng lịch. Dễ dàng quản lý khi nào và bạn đã tập gì.',
    'home.features.detailed.title': 'Bản Ghi Tập Luyện Chi Tiết',
    'home.features.detailed.description': 'Ghi lại hiệp, trọng lượng và số lần lặp lại cho mỗi bài tập. Tổng khối lượng được tính tự động.',
    'home.features.bodypart.title': 'Quản Lý Theo Bộ Phận Cơ Thể',
    'home.features.bodypart.description': 'Tổ chức bài tập theo các bộ phận cơ thể như ngực, vai, cánh tay, lưng, chân và bụng.',
    'home.features.multilang.title': 'Hỗ Trợ 19 Ngôn Ngữ',
    'home.features.multilang.description': 'Hỗ trợ 19 ngôn ngữ bao gồm tiếng Nhật, tiếng Anh, tiếng Tây Ban Nha, tiếng Trung và tiếng Hàn.',
    'home.features.units.title': 'Chuyển Đổi Đơn Vị',
    'home.features.units.description': 'Chuyển đổi đơn vị trọng lượng giữa kilôgam (kg) và pao (lb). Ghi lại theo đơn vị bạn thích.',
    'home.features.darkmode.title': 'Hỗ Trợ Chế Độ Tối',
    'home.features.darkmode.description': 'Chọn giữa chế độ sáng, chế độ tối hoặc theo cài đặt hệ thống.',
    'home.languages.title': 'Ngôn Ngữ Được Hỗ Trợ',
    'home.languages.subtitle': 'Có sẵn cho người dùng trên toàn thế giới',
    'footer.tagline': 'Ghi Chép và Tiếp Tục Phát Triển',
    'footer.links': 'Liên Kết',
    'footer.privacy': 'Chính Sách Bảo Mật',
    'footer.terms': 'Điều Khoản Dịch Vụ',
    'footer.contact': 'Liên Hệ',
    'footer.contact.title': 'Liên Hệ Với Chúng Tôi',
    'privacy.title': 'Chính Sách Bảo Mật',
    'privacy.updated': 'Cập nhật lần cuối: 4 tháng 10 năm 2025',
    'terms.title': 'Điều Khoản Dịch Vụ',
    'terms.updated': 'Cập nhật lần cuối: 4 tháng 10 năm 2025',
    'contact.title': 'Liên Hệ Với Chúng Tôi',
    'contact.description': 'Đừng ngần ngại liên hệ với chúng tôi với bất kỳ câu hỏi, phản hồi hoặc báo cáo lỗi nào về MASCALE',
    'contact.email.title': 'Liên Hệ qua Email',
    'contact.language.title': 'Ngôn Ngữ Được Hỗ Trợ',
    'contact.language.value': 'Chỉ tiếng Nhật',
    'contact.response.title': 'Phản Hồi',
    'contact.response.value': 'Chúng tôi sẽ phản hồi nhanh chóng',
  },
  ar: {
    'header.privacy': 'الخصوصية',
    'header.terms': 'الشروط',
    'header.contact': 'اتصل',
    'home.hero.badge': 'تطبيق سجل التدريب',
    'home.hero.tagline': 'سجل واستمر في التطور',
    'home.hero.description': 'تصور تقدمك بسجلات تدريب\nبسيطة وبديهية',
    'home.hero.download': 'تنزيل على App Store',
    'home.features.title': 'الميزات الرئيسية',
    'home.features.subtitle': 'MASCALE يدعم تدريبك',
    'home.features.calendar.title': 'سجلات التقويم',
    'home.features.calendar.description': 'اعرض تاريخ تدريبك بنظرة سريعة بتنسيق التقويم. إدارة سهلة لما تدربت عليه ومتى.',
    'home.features.detailed.title': 'سجلات تدريب مفصلة',
    'home.features.detailed.description': 'سجل المجموعات والوزن والتكرارات لكل تمرين. يتم حساب الحجم الإجمالي تلقائيًا.',
    'home.features.bodypart.title': 'إدارة أجزاء الجسم',
    'home.features.bodypart.description': 'نظم التمارين حسب أجزاء الجسم مثل الصدر والكتفين والذراعين والظهر والساقين والبطن.',
    'home.features.multilang.title': 'دعم 19 لغة',
    'home.features.multilang.description': 'يدعم 19 لغة بما في ذلك اليابانية والإنجليزية والإسبانية والصينية والكورية.',
    'home.features.units.title': 'تبديل الوحدات',
    'home.features.units.description': 'قم بالتبديل بين وحدات الوزن بين الكيلوجرام (كجم) والرطل (رطل). سجل بالوحدة المفضلة لديك.',
    'home.features.darkmode.title': 'دعم الوضع الداكن',
    'home.features.darkmode.description': 'اختر بين الوضع الفاتح أو الوضع الداكن أو اتبع إعدادات النظام.',
    'home.languages.title': 'اللغات المدعومة',
    'home.languages.subtitle': 'متاح للمستخدمين في جميع أنحاء العالم',
    'footer.tagline': 'سجل واستمر في التطور',
    'footer.links': 'روابط',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.contact': 'اتصل',
    'footer.contact.title': 'اتصل بنا',
    'privacy.title': 'سياسة الخصوصية',
    'privacy.updated': 'آخر تحديث: 4 أكتوبر 2025',
    'terms.title': 'شروط الخدمة',
    'terms.updated': 'آخر تحديث: 4 أكتوبر 2025',
    'contact.title': 'اتصل بنا',
    'contact.description': 'لا تتردد في الاتصال بنا بأي أسئلة أو ملاحظات أو تقارير أخطاء حول MASCALE',
    'contact.email.title': 'الاتصال عبر البريد الإلكتروني',
    'contact.language.title': 'اللغة المدعومة',
    'contact.language.value': 'اليابانية فقط',
    'contact.response.title': 'الرد',
    'contact.response.value': 'سنرد بسرعة',
  },
  hi: {
    'header.privacy': 'गोपनीयता',
    'header.terms': 'शर्तें',
    'header.contact': 'संपर्क',
    'home.hero.badge': 'प्रशिक्षण लॉग ऐप',
    'home.hero.tagline': 'रिकॉर्ड करें और विकसित होते रहें',
    'home.hero.description': 'सरल और सहज प्रशिक्षण रिकॉर्ड के साथ\nअपनी प्रगति की कल्पना करें',
    'home.hero.download': 'App Store पर डाउनलोड करें',
    'home.features.title': 'मुख्य विशेषताएं',
    'home.features.subtitle': 'MASCALE आपके प्रशिक्षण का समर्थन करता है',
    'home.features.calendar.title': 'कैलेंडर रिकॉर्ड',
    'home.features.calendar.description': 'कैलेंडर प्रारूप में एक नज़र में अपने प्रशिक्षण इतिहास को देखें। आसानी से प्रबंधित करें कि आपने कब और क्या प्रशिक्षण लिया।',
    'home.features.detailed.title': 'विस्तृत प्रशिक्षण रिकॉर्ड',
    'home.features.detailed.description': 'प्रत्येक व्यायाम के लिए सेट, वजन और दोहराव रिकॉर्ड करें। कुल मात्रा स्वचालित रूप से गणना की जाती है।',
    'home.features.bodypart.title': 'शरीर के अंग प्रबंधन',
    'home.features.bodypart.description': 'छाती, कंधे, बाहें, पीठ, पैर और पेट जैसे शरीर के अंगों द्वारा व्यायाम को व्यवस्थित करें।',
    'home.features.multilang.title': '19 भाषा समर्थन',
    'home.features.multilang.description': 'जापानी, अंग्रेजी, स्पेनिश, चीनी और कोरियाई सहित 19 भाषाओं का समर्थन करता है।',
    'home.features.units.title': 'इकाई स्विचिंग',
    'home.features.units.description': 'किलोग्राम (kg) और पाउंड (lb) के बीच वजन इकाइयों को स्विच करें। अपनी पसंदीदा इकाई में रिकॉर्ड करें।',
    'home.features.darkmode.title': 'डार्क मोड समर्थन',
    'home.features.darkmode.description': 'लाइट मोड, डार्क मोड के बीच चुनें या सिस्टम सेटिंग्स का पालन करें।',
    'home.languages.title': 'समर्थित भाषाएं',
    'home.languages.subtitle': 'दुनिया भर के उपयोगकर्ताओं के लिए उपलब्ध',
    'footer.tagline': 'रिकॉर्ड करें और विकसित होते रहें',
    'footer.links': 'लिंक',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.contact': 'संपर्क',
    'footer.contact.title': 'हमसे संपर्क करें',
    'privacy.title': 'गोपनीयता नीति',
    'privacy.updated': 'अंतिम अपडेट: 4 अक्टूबर 2025',
    'terms.title': 'सेवा की शर्तें',
    'terms.updated': 'अंतिम अपडेट: 4 अक्टूबर 2025',
    'contact.title': 'हमसे संपर्क करें',
    'contact.description': 'MASCALE के बारे में किसी भी प्रश्न, फीडबैक या बग रिपोर्ट के साथ हमसे संपर्क करने में संकोच न करें',
    'contact.email.title': 'ईमेल द्वारा संपर्क',
    'contact.language.title': 'समर्थित भाषा',
    'contact.language.value': 'केवल जापानी',
    'contact.response.title': 'प्रतिक्रिया',
    'contact.response.value': 'हम शीघ्र प्रतिक्रिया देंगे',
  },
  fa: {
    'header.privacy': 'حریم خصوصی',
    'header.terms': 'شرایط',
    'header.contact': 'تماس',
    'home.hero.badge': 'برنامه گزارش تمرین',
    'home.hero.tagline': 'ثبت کنید و به تکامل ادامه دهید',
    'home.hero.description': 'پیشرفت خود را با گزارش‌های تمرینی\nساده و شهودی تجسم کنید',
    'home.hero.download': 'دانلود در App Store',
    'home.features.title': 'ویژگی‌های کلیدی',
    'home.features.subtitle': 'MASCALE از تمرین شما پشتیبانی می‌کند',
    'home.features.calendar.title': 'گزارش‌های تقویم',
    'home.features.calendar.description': 'تاریخچه تمرین خود را در یک نگاه در قالب تقویم مشاهده کنید. به راحتی مدیریت کنید که چه وقت و چه چیزی تمرین کرده‌اید.',
    'home.features.detailed.title': 'گزارش‌های تمرینی تفصیلی',
    'home.features.detailed.description': 'ست‌ها، وزن و تکرارها را برای هر تمرین ثبت کنید. حجم کل به طور خودکار محاسبه می‌شود.',
    'home.features.bodypart.title': 'مدیریت بخش‌های بدن',
    'home.features.bodypart.description': 'تمرین‌ها را بر اساس بخش‌های بدن مانند سینه، شانه، بازو، کمر، پا و شکم سازماندهی کنید.',
    'home.features.multilang.title': 'پشتیبانی از 19 زبان',
    'home.features.multilang.description': 'از 19 زبان از جمله ژاپنی، انگلیسی، اسپانیایی، چینی و کره‌ای پشتیبانی می‌کند.',
    'home.features.units.title': 'تغییر واحد',
    'home.features.units.description': 'واحدهای وزن را بین کیلوگرم (kg) و پوند (lb) تغییر دهید. در واحد مورد علاقه خود ثبت کنید.',
    'home.features.darkmode.title': 'پشتیبانی از حالت تاریک',
    'home.features.darkmode.description': 'بین حالت روشن، حالت تاریک انتخاب کنید یا از تنظیمات سیستم پیروی کنید.',
    'home.languages.title': 'زبان‌های پشتیبانی‌شده',
    'home.languages.subtitle': 'برای کاربران در سراسر جهان در دسترس است',
    'footer.tagline': 'ثبت کنید و به تکامل ادامه دهید',
    'footer.links': 'پیوندها',
    'footer.privacy': 'سیاست حریم خصوصی',
    'footer.terms': 'شرایط خدمات',
    'footer.contact': 'تماس',
    'footer.contact.title': 'با ما تماس بگیرید',
    'privacy.title': 'سیاست حریم خصوصی',
    'privacy.updated': 'آخرین به‌روزرسانی: 4 اکتبر 2025',
    'terms.title': 'شرایط خدمات',
    'terms.updated': 'آخرین به‌روزرسانی: 4 اکتبر 2025',
    'contact.title': 'با ما تماس بگیرید',
    'contact.description': 'برای هرگونه سوال، بازخورد یا گزارش اشکال در مورد MASCALE با ما تماس بگیرید',
    'contact.email.title': 'تماس از طریق ایمیل',
    'contact.language.title': 'زبان پشتیبانی‌شده',
    'contact.language.value': 'فقط ژاپنی',
    'contact.response.title': 'پاسخ',
    'contact.response.value': 'ما به سرعت پاسخ خواهیم داد',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ja')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language | null
    const validLanguages: Language[] = ['ja', 'en', 'es', 'pt', 'de', 'fr', 'zh', 'ko', 'it', 'id', 'ru', 'tr', 'nl', 'pl', 'th', 'vi', 'ar', 'hi', 'fa']
    if (savedLanguage && validLanguages.includes(savedLanguage)) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ja']] || translations['en'][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
